#!/usr/bin/env bash

set -e

export PATH="/home/richyliu/neojetset-qemu/build:$PATH"

qemu-system-x86_64 \
  -m 512 \
  -drive if=virtio,format=qcow2,file=disk2.qcow2 \
  -drive if=virtio,format=raw,file=seed.img \
  -device virtio-net-pci,netdev=net0 \
  -netdev user,id=net0,hostfwd=tcp::2222-:22 \
  -device snapshot \
  -no-reboot \
  -enable-kvm \
  -nographic
