#!/usr/bin/env bash

set -e

lldb="eval"
if [[ $# = 1 ]]; then
    lldb="lldb"
    echo "process handle --pass true --stop false --notify false SIGUSR2"
    echo "^ run command after a SIGUSR2"
fi

export PATH="/home/richyliu/neojetset-qemu/build:$PATH"

# username: root, password: alpine

# to restore (with -incoming defer):
# migrate_incoming "exec:cat migration_file_name"
    # -incoming defer \

    # -device edu \
    # -device snapshot \

# on guest:
# https://unix.stackexchange.com/questions/230650/how-can-i-know-which-serial-port-corresponds-to-a-pci-card
# - list devices with: lspci -v
# - look for serial device
# - correlate id with list from: setserial -g /dev/ttyS*
# - usually on /dev/ttyS1 (?)

# to connect over ssh:
# ssh -p 2222 ubuntu@0.0.0.0

# to connect to serial device: socat - UNIX-CONNECT:/tmp/my_snapshot
# NOTE: important to put -device snapshot after -device pci-serial
"$lldb" -- \
  qemu-system-x86_64 \
    -m 512 \
    -drive if=virtio,format=qcow2,file=disk2.qcow2 \
    -drive if=virtio,format=raw,file=seed.img \
    -device virtio-net-pci,netdev=net0 \
    -netdev user,id=net0,hostfwd=tcp::2222-:22 \
    -chardev socket,path=/tmp/my_snapshot,server=on,wait=off,id=snapshot \
    -device pci-serial,chardev=snapshot \
    -device snapshot \
    -no-reboot \
    -enable-kvm \
    -nographic
